export enum TestIdName {
    AllergensAddBtn = 'add-allergen-button',
    AllergensAddInput = 'add-other-allergen',
    AllergensCheckbox = 'allergen',
    AllergensMenu = 'allergens-menu',
    AllergensMenuBtn = 'allergens-menu-button',
    AllergensMenuBtnFilter = 'allergens-menu-button-filter',
    AllergensSwitcher = 'allergens-switcher',
    AllergensSwitcherFilter = 'allergens-switcher-filter',

    BloggerFollowersBookmarks = 'blogger-followers-bookmarks',
    BloggerFollowersCount = 'blogger-followers-count',
    BloggerUserBreadcrumbName = 'blogger-user-breadcrumb-name',
    BloggerUserBreadcrumbSection = 'blogger-user-breadcrumb-section',
    BloggerUserInfoBox = 'blogger-user-info-box',
    BloggerUserInfoLogin = 'blogger-user-info-login',
    BloggerUserInfoName = 'blogger-user-info-name',
    BloggerUserNotesButton = 'blogger-user-notes-button',
    BloggerUserNotesCount = 'blogger-user-notes-count',
    BloggerUserNotesGrid = 'blogger-user-notes-grid',
    BloggerUserOtherBlogsButton = 'blogger-user-other-blogs-button',
    BloggerUserOtherBlogsGrid = 'blogger-user-other-blogs-grid',
    BlogNotesBox = 'blog-notes-box',
    BlogsCard = 'blogs-card',
    BlogsCardLogin = 'blogs-card-login',
    BlogsCardName = 'blogs-card-name',
    BlogsCardNewRecipesBadge = 'blogs-card-new-recipes-badge',
    BlogsCardNotesButton = 'blogs-card-notes-button',
    BlogsCardNotesText = 'blogs-card-notes-text',
    BlogsCardRecipesButton = 'blogs-card-recipes-button',
    BlogsFavoritesBox = 'blogs-favorites-box',
    BlogsFavoritesGrid = 'blogs-favorites-grid',
    BlogsOthersBox = 'blogs-others-box',
    BlogsOthersButton = 'blogs-others-button',
    BlogsOthersGrid = 'blogs-others-grid',
    BlogToggleSubscribe = 'blog-toggle-subscribe',
    BlogToggleUnsubscribe = 'blog-toggle-unsubscribe',
    BlogTooltip = 'blog-tooltip',

    Breadcrumbs = 'breadcrumbs',
    BurgerCloseIcon = 'close-icon',

    BurgerNav = 'nav',
    BurgerOpenIcon = 'hamburger-icon',

    CardLink = 'card-link',

    Carousel = 'carousel',
    CarouselBack = 'carousel-back',
    CarouselForward = 'carousel-forward',

    Checkbox = 'checkbox',

    ErrorNotif = 'error-notification',
    ErrorNotifClose = 'close-alert-button',
    ErrorNotificationDescription = 'error-notification-description',
    ErrorNotificationTitle = 'error-notification-title',
    ErrorPageHome = 'error-page-go-home',

    FilterCategory = 'filter-menu-button-категория',
    FilterClearBtn = 'clear-filter-button',
    FilterCloseBtn = 'close-filter-drawer',
    FilterDrawer = 'filter-drawer',
    FilterFindBtn = 'find-recipe-button',
    FilterOpenBtn = 'filter-button',
    FilterTag = 'filter-tag',

    Footer = 'footer',
    ForgotPassword = 'forgot-password',
    Header = 'header',
    HeaderLogo = 'header-logo',
    IngredientQuantity = 'ingredient-quantity',

    InputEmail = 'email-input',
    InputFile = 'input-file',
    InputFirstName = 'first-name-input',
    InputLastName = 'last-name-input',
    InputLogin = 'login-input',
    InputPassword = 'password-input',
    InputPasswordConfirm = 'confirm-password-input',
    InputVerificationCode = 'verification-code-input',

    JuiciestLink = 'juiciest-link',
    JuiciestLinkMobile = 'juiciest-link-mobile',

    LoaderApp = 'app-loader',
    LoaderMobile = 'mobile-loader',
    LoaderSearch = 'loader-search-block',

    LoadMoreBtn = 'load-more-button',

    MainPageBlogsBox = 'main-page-blogs-box',
    MainPageBlogsButton = 'main-page-blogs-button',
    MainPageBlogsGrid = 'main-page-blogs-grid',

    MenuActive = 'active',

    ModalClose = 'close-button',
    ModalEmailVerificationFailed = 'email-verification-failed-modal',
    ModalResetCredentials = 'reset-credentials-modal',
    ModalSendEmail = 'send-email-modal',
    ModalSignIn = 'sign-in-error-modal',
    ModalSignUpSuccess = 'sign-up-success-modal',
    ModalVerificationCode = 'verification-code-modal',

    NotesCardDate = 'notes-card-date',
    NotesCardText = 'notes-card-text',

    PasswordBtn = 'password-visibility-button',
    PreventiveModal = 'recipe-preventive-modal',
    PreviewImage = 'preview-image',

    RecipeAddIngredientsButton = 'recipe-ingredients-add-ingredients',
    RecipeAddRecipeButton = 'add-recipe-button',
    RecipeCardList = 'recipe-card-list',
    RecipeCategories = 'recipe-categories',
    RecipeDeleteButton = 'recipe-delete-button',
    RecipeDescription = 'recipe-description',
    RecipeForm = 'recipe-form',
    RecipeImageBlock = 'recipe-image-block',
    RecipeImageBlockInputFile = 'recipe-image-block-input-file',
    RecipeImageBlockPreviewImage = 'recipe-image-block-preview-image',
    RecipeImageModal = 'recipe-image-modal',
    RecipeImageModalImageBlock = 'recipe-image-modal-image-block',
    RecipeImageModalPreviewImage = 'recipe-image-modal-preview-image',
    RecipeIngredientsCount = 'recipe-ingredients-count',
    RecipeIngredientsMeasureUnit = 'recipe-ingredients-measureUnit',
    RecipeIngredientsRemoveIngredients = 'recipe-ingredients-remove-ingredients',
    RecipeIngredientsTitle = 'recipe-ingredients-title',
    RecipePortions = 'recipe-portions',
    RecipePublishButton = 'recipe-publish-recipe-button',
    RecipeSaveDraftButton = 'recipe-save-draft-button',
    RecipeStepsDescription = 'recipe-steps-description',
    RecipeStepsImageBlock = 'recipe-steps-image-block',
    RecipeStepsRemoveButton = 'recipe-steps-remove-button',
    RecipeTime = 'recipe-time',
    RecipeTitle = 'recipe-title',

    RepeatBtn = 'repeat-button',
    SearchBtn = 'search-button',
    SearchInput = 'search-input',
    SignInForm = 'sign-in-form',
    SignUpForm = 'sign-up-form',
    SignUpProgress = 'sign-up-progress',
    StepperDecrement = 'decrement-stepper',
    StepperIncrement = 'increment-stepper',
    SubmitBtn = 'submit-button',
    Tab = 'tab',
}
