export enum ApiEndpoints {
    RECIPE = '/recipe',
    RECIPE_DRAFT = '/recipe/draft',
    RECIPIES_BY_CATEGORY = '/recipe/category',
    RECIPIES_BY_USER = '/recipe/user',
    CATEGORY = '/category',
    AUTH_SIGNUP = '/auth/signup',
    AUTH_LOGIN = '/auth/login',
    AUTH_REFRESH = '/auth/refresh',
    AUTH_CHECK_AUTH = '/auth/check-auth',
    AUTH_VERIFY_EMAIL = '/auth/verify',
    AUTH_FORGOT_PASSWORD = '/auth/forgot-password',
    AUTH_VERIFY_OTP = '/auth/verify-otp',
    AUTH_RESET_PASSWORD = '/auth/reset-password',
    MEASURE_UNITS = 'measure-units',
    LIKE = 'like',
    BOOKMARK = 'bookmark',
    UPLOAD_FILE = '/file/upload',
}
