export enum EndpointNames {
    GET_RECIPES = 'getRecipes',
    GET_NEW_RECIPIES = 'getNewRecipes',
    GET_JUICIEST_RECIPIES = 'getJuiciestRecipes',
    GET_RELEVANT_RECIPIES = 'getRelevantRecipes',
    GET_RECIPIES_BY_CATEGORY = 'getRecipesByCategory',
    GET_RECIPE_BY_ID = 'getRecipeById',
    GET_RECIPIES_BY_USER_ID = 'getRecipeByUser',
    GET_CATEGORIES = 'getCategories',
    GET_CATEGORY_BY_ID = 'getCategoryById',
    AUTH_SIGNUP = 'signup',
    AUTH_LOGIN = 'login',
    AUTH_REFRESH = 'refresh',
    AUTH_CHECK_AUTH = 'checkAuth',
    AUTH_VERIFY_EMAIL = 'verifyEmail',
    AUTH_VERIFY_OTP = 'verifyOTP',
    AUTH_FORGOT_PASSWORD = 'forgotPassword',
    AUTH_RESET_PASSWORD = 'resetPassword',
}
