export enum EndpointNames {
    GET_RECIPES = 'getRecipes',
    GET_NEW_RECIPIES = 'getNewRecipes',
    GET_JUICIEST_RECIPIES = 'getJuiciestRecipes',
    GET_RELEVANT_RECIPIES = 'getRelevantRecipes',
    GET_RECIPIES_BY_CATEGORY = 'getRecipesByCategory',
    GET_RECIPE_BY_ID = 'getRecipeById',
    GET_RECIPIES_BY_USER_ID = 'getRecipeByUser',
    GET_CATEGORIES = 'getCategories',
    GET_CATEGORY_BY_ID = 'getCategoryById',
    AUTH_SIGNUP = 'signupAuth',
    AUTH_LOGIN = 'loginAuth',
    AUTH_REFRESH = 'refreshAuth',
    AUTH_CHECK_AUTH = 'checkAuth',
    AUTH_VERIFY_EMAIL = 'verifyEmailAuth',
    AUTH_VERIFY_OTP = 'verifyOTPAuth',
    AUTH_FORGOT_PASSWORD = 'forgotPasswordAuth',
    AUTH_RESET_PASSWORD = 'resetPasswordAuth',
    CREATE_RECIPE = 'createRecipe',
    UPDATE_RECIPE = 'updateRecipe',
    DELETE_RECIPE = 'deleteRecipe',
    SAVE_RECIPE_DRAFT = 'saveDraft',
    GET_MEASURE_UNITS = 'getMeasureUnits',
    LIKE_RECIPE = 'likeRecipe',
    BOOKMARK_RECIPE = 'bookmarkRecipe',
}
